<?php

setlocale(LC_ALL, "pt_BR", "pt_BR.utf-8", "portuguese");
//A função date não é sensível ao setlocale, para configuração regional,(idioma e fuso horário) por isso, mesmo configurndo aqui a data obedece o padrão americano. Resultado em inglês. A função date, obedece configurações do servidor.

echo "DATA ATUAL <BR>";
echo "Data e Hora: " . date('d-m-Y :: H:i:s');
//Date retorna data e hora.
echo "<br>";
echo "<br>";
echo "<b>FORMATANDO DIA DO MÊS</b> <BR>";
echo "Dia: " . date('d') . ". (d) - retorna dia do mês com 2 dígitos e zero à esquerda";
echo "<br>";
echo "Dia: " . date('D') . ". (D) - Uma representação textual de um dia, três letras.";
echo "<br>";
echo "Dia: " . date('j') . ". (j) Dia do mês sem zero à esquerda.";
echo "<br>";
echo "Dia: " . date('l') . ". (l) A representação textual completa do dia da semana.";
echo "<br>";
echo "Dia: " . date('N') . ". (N) Representação numérica ISO-8601 do dia da semana (adicionado no PHP 5.1.0). 1 - 7; 1 = segunda, 7 = domingo.";
echo "<br>";
echo "Dia Mês: " . date('S') . ". (S) 	Sufixo ordinal inglês para o dia do mês, 2 caracteres.";
echo "<br>";
echo "Dia: " . date('w') . ". (w) Representação numérica do dia da semana. - 0 (para domingo) até 6 (para sábado).";
echo "<br>";
echo "<br>";
echo "Dia do Ano: " . date('z') . ". (z) O dia do ano (iniciando em 0) - 0 até 365.";
echo "<br>";
echo "<br>";
echo "<b>FORMATAÇÃO PARA SEMANA</b> <BR>";
echo "Ano da Semana: " . date('W') . ". (W) Número do ano da semana SO-8601, começa na Segunda (adicionado no PHP 4.1.0). Exemplo: 42 (a 42ª semana do ano)";
echo "<br>";
echo "<br>";
echo "<b>FORMATAÇÃO PARA MÊS</b> <BR>";
echo "Mês Extenso: " . date('F') . " - 'F' Um representação completa de um mês, como January ou March.";
echo "<br>";
echo "Mês Numérico: " . date('m') . " - 'm' Representação numérica de um mês, com zero à esquerd.";
echo "<br>";
echo "Mês Abreviado: " . date('M') . " - 'M' Uma representação textual curta de um mês, três letras.";
echo "<br>";
echo "Mês Numérico: " . date('n') . " - 'n' Representação numérica de um mês, sem zero à esquerda.";
echo "<br>";
echo "Número de dias de um mês: " . date('t') . " - 't' Nº dias que tem no mês.";
echo "<br>";
echo "<br>";
echo "<b>FORMATAÇÃO PARA ANO </b><BR>";
echo "<br>";
echo "Bissexto?: " . date('L') . " - 'L' Verifica ano bissexto. - Retorna 1 se for ano bissexto, 0, para não.";
echo "<br>";
echo "<br>";
echo "Número do ano: " . date('o') . " - 'o' Número do ano ISO-8601. Este tem o mesmo valor como Y, exceto que se o número da semana ISO (W) pertence ao anterior ou próximo ano, o ano é usado ao invés. (adicionado no PHP 5.1.0). - Exemplos: 1999 ou 2003";
echo "<br>";
echo "Ano Completo: " . date('Y') . "'Y' Uma representação do ano com 4 dígitos.";
echo "<br>";
echo "Ano Completo: " . date('y') . "'y' Uma representação do ano com 2 dígitos.";
echo "<br>";
echo "<br>";
echo "<b>FORMATAÇÃO PARA TEMPO </b><BR>";
echo "am pm (minúsculo): " . date('h:i:s - a') . ". (a) Antes/Depois de meio-dia em minúsculo.";
echo "<br>";
echo "AM PM (minúsculo): " . date('h:i:s - A') . ". (A) Antes/Depois de meio-dia em minúsculo.";
echo "<br>";
echo "Swatch: " . date('B') . ". (B) Swatch Internet time. Tempo da Internet.";
echo "<br>";
echo "Formato 12h: " . date('g') . " - 'g' Formato 12-horas de uma hora sem zero à esquerda.";
echo "<br>";
echo "Formato 24h: " . date('G') . " - 'G' Formato 24-horas de uma hora sem zero à esquerda.";
echo "<br>";
echo "Formato 12h: " . date('h') . " - 'h' Formato 12-horas de uma hora com zero à esquerda.";
echo "<br>";
echo "Formato 24h: " . date('H') . " - 'H' Formato 24-horas de uma hora com zero à esquerda.";
echo "<br>";
echo "Minuto com zero à esquerda: " . date('i') . " - 'i' Minutos com zero à esquerda.";
echo "<br>";
echo "Segundos com zero à esquerda: " . date('s') . " - 's' Segundos com zero à esquerda.";
echo "<br>";
echo "<br>";
echo "Microssegundos com zero à esquerda: " . date('u') . " - 'u' Microssegundos (adicionado no PHP 5.2.2). Note que a função date() sempre gerará 000000, já que aceita um parâmetro integer, enquanto que DateTime::format() possui suporte a microssegundos se DateTime foi criado com microssegundos. Example: 654321";
echo "<br>";
